fix(dot): provide error message if `darwin-rebuild` fails

diff --git a/bin/dotfield b/bin/dotfield
--- a/bin/dotfield
+++ b/bin/dotfield
@@ -43,7 +43,9 @@ function __switch() {
   local output="$2"
   local rebuild="${dir}/result/sw/bin/darwin-rebuild"
   [[ -e "${rebuild}" ]] && {
-    "${rebuild}" switch -v --flake "$(__flake_path "${dir}" "${output}")"
+    "${rebuild}" switch -v --flake "$(__flake_path "${dir}" "${output}")" || {
+      msg::error "Failed to switch to the new generation!"
+    }
   }
 }
 
