fix(crypt): force run

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -694,13 +694,16 @@ guard::macos && {
 guard::install && {
   msg::domain "Guardian" "Decrypting Dotfield secrets"
   if [[ $(gpg --list-secret-keys "${DOTFIELD_ID_EMAIL}" 2>/dev/null) ]]; then
-    transcrypt --yes --import-gpg="${XDG_CONFIG_HOME}/.transcrypt" || {
-      git status
+    # Force transcrypt to run even if it thinks the working tree is dirty.
+    # This seems to be a false positive. Regardless, we've already checked for
+    # a dirty working tree so nothing should be lost at this point.
+    transcrypt --yes --force --import-gpg="${XDG_CONFIG_HOME}/.transcrypt" || {
       msg::error "Something went wrong!"
       exit 1
     }
   else
-    msg::warning "The requisite GPG key was not found! Cannot decrypt the secrets of Dotfield..."
+    msg::error "The requisite GPG key was not found! Cannot decrypt the secrets of Dotfield..."
+    exit 1
   fi
 }
 
