feat(bootstrap): allow continuation of user provisioning

diff --git a/provision/debian/main b/provision/debian/main
--- a/provision/debian/main
+++ b/provision/debian/main
@@ -7,6 +7,8 @@
 . "${DOTFIELD_DIR}/lib/utils.sh"
 
 function __provision_user {
+  local user_exists
+
   if [[ -n "${DOTFIELD_USERNAME}" ]]; then
     USERNAME="${DOTFIELD_USERNAME}"
   else
@@ -15,30 +17,45 @@ function __provision_user {
   fi
 
   user::exists "${USERNAME}" && {
-    # TODO: attempt to provision the user instead
-    msg::error "[ERROR] The user '${USERNAME}' already exists! Aborting."
-    return 1
+    user_exists=true
+
+    msg::warning "[ERROR] The user '${USERNAME}' already exists!"
+    msg::ask_for_confirmation "Do you want to continue provisioning this user?"
+    msg::is_confirmed || {
+      msg::error "Aborting."
+      return 1
+    }
   }
 
   readonly USERNAME
 
-  if [[ -n "${DOTFIELD_USER_PASSWORD}" ]]; then
-    PASSWORD="${DOTFIELD_USER_PASSWORD}"
-  else
-    user::prompt_for_password
+  if [[ -z "$user_exists" ]]; then
+    msg::subdomain "Creating user account"
+    if [[ -n "${DOTFIELD_USER_PASSWORD}" ]]; then
+      PASSWORD="${DOTFIELD_USER_PASSWORD}"
+    else
+      user::prompt_for_password
+    fi
+
+    user::create_account "${USERNAME}" "${PASSWORD}"
   fi
 
-  user::create_account "${USERNAME}" "${PASSWORD}"
-
   if [[ -n "${DOTFIELD_SSH_PUBLIC_KEY}" ]]; then
+    msg::subdomain "Setting SSH public key for ${USERNAME}"
     user::add_ssh_pub_key "${USERNAME}" "${DOTFIELD_SSH_PUBLIC_KEY}"
   else
+    msg::subdomain "Cloning SSH config for ${USERNAME} from root user"
     user::clone_ssh "${USER}" "${USERNAME}"
   fi
 
-  user::allow_passwordless_sudo "${USERNAME}" \
-    && user::change_ssh_config \
-    && user::set_ssh_permissions
+  msg::subdomain "Adding ${USERNAME} as sudoer"
+  user::allow_passwordless_sudo "${USERNAME}"
+
+  msg::subdomain "Require passwordless login and disable root SSH login"
+  user::change_ssh_config
+
+  msg::subdomain "Ensuring proper permissions on SSH directory for ${USERNAME}"
+  user::set_ssh_permissions "${USERNAME}"
 
   print_result $? "Configure SSH"
 }
